name: flutter_application_1
description: "MySalon - Salon Booking App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  provider: ^6.1.5+1
  cloud_firestore: ^6.0.3
  google_maps_flutter: ^2.13.1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  google_maps_flutter_web: ^0.5.14+2
  geolocator_web: ^4.1.3
  geocoding: ^4.0.0
  url_launcher: ^6.3.2
  flutter_secure_storage: ^9.2.4
  country_picker: ^2.0.27
  flutter_libphonenumber: ^2.5.1
  flutter_multi_formatter: ^2.13.10
  cloud_functions: ^6.0.4
  connectivity_plus: ^7.0.0
  http: ^1.6.0
  web: ^1.1.1
  supabase_flutter: ^2.12.0
  go_router: ^17.0.1
  flutter_dotenv: ^6.0.0
  url_strategy: ^0.3.0
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.3
  package_info_plus: ^9.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ========== FLUTTER LAUNCHER ICONS CONFIG meka use karanne icon auto genarate karagnna==========
flutter_launcher_icons:
  # Android icons
  android: true
  image_path_android: "assets/logo.png"
  adaptive_icon_background: "#FF6B8B"
  adaptive_icon_foreground: "assets/logo.png"
  
  # iOS icons  
  ios: true
  image_path_ios: "assets/logo.png"
  remove_alpha_ios: true
  
  # Web icons
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#FF6B8B"

# ========== FLUTTER CONFIG ==========
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env